project_id = "vvabffebndtzellpnomq"

[functions.conta-azul-auth]
verify_jwt = false

[functions.conta-azul-data]
verify_jwt = false

[functions.sync-conta-azul]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-toggle-role]
verify_jwt = true

