project_id = "vvabffebndtzellpnomq"

[functions.conta-azul-auth]
verify_jwt = false

[functions.conta-azul-data]
verify_jwt = false

[functions.sync-conta-azul]
verify_jwt = true

[functions.clear-synced-data]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-toggle-role]
verify_jwt = true

[functions.daily-sync-job]
verify_jwt = false

[functions.save-conta-azul-tokens]
verify_jwt = true

[functions.send-sync-notification]
verify_jwt = false

[functions.test-conta-azul-categories]
verify_jwt = true

[functions.fetch-sheets-faturamento]
verify_jwt = false
